server:
  port: 8090
  maxPostSize: 0
spring:
  application.name: api
  profiles.active: dev
  #thymeleaf
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html


#而当我们需要使用CGLIB来实现AOP的时候，需要配置 spring.aop.proxy-target-class=true ，不然默认使用的是标准Java的实现
spring.aop.proxy-target-class: true

#JACKSON
spring.jackson:
  date-format: "yyyy-MM-dd HH:mm:ss"
  default-property-inclusion: NON_NULL
  time-zone: GMT+8


#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql




---
spring.profiles: dev
spring.profiles.include: dao







